steps:
# 1. Constrói a imagem do contêiner
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/concierge-pro:$COMMIT_SHA', '.']

# 2. Envia a imagem para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/concierge-pro:$COMMIT_SHA']

# 3. Implanta a nova imagem no Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'concierge-pro-service' # Nome do nosso serviço no Cloud Run
    - '--image=gcr.io/$PROJECT_ID/concierge-pro:$COMMIT_SHA'
    - '--region=southamerica-east1'
    - '--platform=managed'
    - '--allow-unauthenticated'

# --- ADICIONADO: Configuração de Opções de Logging ---
options:
  logging: CLOUD_LOGGING_ONLY
