steps:
  # 1. Constrói a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro-repo/concierge-pro-app:$SHORT_SHA', '.']

  # 2. Envia a imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro-repo/concierge-pro-app:$SHORT_SHA']

  # 3. Executa as migrações do banco de dados com Alembic
  - name: 'gcr.io/google-appengine/exec-wrapper'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        /exec_wrapper \
          -i southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro-repo/concierge-pro-app:$SHORT_SHA \
          -e DATABASE_URL=${_DATABASE_URL} \
          -- \
          alembic upgrade head

  # 4. Implanta a nova versão no Cloud Run
  - name: 'gcr.io/google-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'concierge-pro-service'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro-repo/concierge-pro-app:$SHORT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets=TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,DATABASE_URL=DATABASE_URL:latest'
      - '--update-env-vars=WEBHOOK_URL=${_WEBHOOK_URL}'

# Configuração de logging para corrigir o erro do build
options:
  logging: CLOUD_LOGGING_ONLY
