steps:
  # 1. Constrói a imagem do contêiner
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA', '.']

  # 2. Envia a imagem para o Artifact Registry no Brasil
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA']

  # 3. Executa as migrações usando a própria imagem da aplicação
  # USA A VERSÃO SEGURA COM VARIÁVEL DE SUBSTITUIÇÃO
  - name: 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA'
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
    entrypoint: 'alembic'
    args:
      - '-c'
      - 'alembic.ini'
      - 'upgrade'
      - 'head'

  # 4. Implanta a nova versão no Cloud Run
  - name: 'gcr.io/google-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'concierge-pro-service'
      - '--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA'
      - '--region=southamerica-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,DATABASE_URL=DATABASE_URL:latest'
      - '--update-env-vars=WEBHOOK_URL=${_WEBHOOK_URL}'

options:
  logging: CLOUD_LOGGING_ONLY
