steps:
  # 1. Constrói a imagem do contêiner
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA', '.']

  # 2. Envia a imagem para o Artifact Registry no Brasil
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA']

  # 3. Debug: Lista os arquivos no diretório
  # Este passo foi adicionado para depurar o erro do Alembic
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA'
      - '-e'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--'
      - 'ls'
      - '-la'
    id: 'Debug Files'

  # 4. Executa as migrações do banco de dados
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA'
      - '-e'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--'
      - 'alembic'
      - '-c'
      - 'alembic.ini'
      - 'upgrade'
      - 'head'

  # 5. Implanta a nova versão no Cloud Run
  - name: 'gcr.io/google-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'concierge-pro-service' # Nome do nosso serviço no Cloud Run
      - '--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/concierge-pro/concierge-pro-service:$COMMIT_SHA'
      - '--region=southamerica-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,DATABASE_URL=DATABASE_URL:latest'
      - '--update-env-vars=WEBHOOK_URL=${_WEBHOOK_URL}'

# Configuração de logging para o build
options:
  logging: CLOUD_LOGGING_ONLY
